const COMMANDS: &[&str] = &[
    "agent_bridge_response",
    "agent_attach",
    "agent_snapshot",
    "agent_find",
    "agent_action",
    "agent_inspect",
    "agent_eval",
    "agent_type",
    "agent_select",
    "agent_check",
    "agent_hover",
    "agent_focus",
    "agent_blur",
    "agent_scroll",
    "agent_drag",
    "agent_screenshot",
    "agent_logs",
    "agent_events",
    "agent_network",
    "agent_ipc",
    "agent_storage",
    "agent_cookies",
    "agent_location",
    "agent_windows",
    "agent_window",
    "agent_wait",
    "agent_expect",
    "agent_state",
    "agent_record",
    "agent_stream",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS).build();
}
